SELECT TOP (1000) [Id]
      ,[ItemName]
      ,[ItemCode]
      ,[Category]
      ,[Location]
      ,[Quantity]
      ,[UnitPrice]
      ,[Status]
      ,[Description]
      ,[CreatedDate]
      ,[UpdatedDate]
  FROM [OcdItInventoryDb].[dbo].[InventoryItems]
